syntax = "proto3";

option csharp_namespace = "ModbusData.GrpcProtos";

package GrpcProtos;

import "google/protobuf/wrappers.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/struct.proto";
import "common.proto"; 
import "digitalvariable.proto";

// Definición del servicio para gestionar AnalogicVariables
service AnalogicVariable {
    rpc CreateAnalogicVariable(CreateAnalogicVariableRequest) returns (AnalogicVariableDTO);
    rpc GetAnalogicVariable(GetRequest) returns (NullableAnalogicVariableDTO);
    rpc GetAllAnalogicVariables(google.protobuf.Empty) returns (AnalogicVariables);
    rpc UpdateAnalogicVariable(AnalogicVariableDTO) returns (google.protobuf.Empty);
    rpc DeleteAnalogicVariable(DeleteRequest) returns (google.protobuf.Empty);
}

// DTO para AnalogicVariable
message AnalogicVariableDTO {
    string id = 1; // Identificador único
    string name = 2; // Nombre de la variable
    VariableType type = 3; // Tipo de la variable (Digital o Analógica)
    bool isMeasurement = 4; // ¿Es una medición?
    string code = 5; // Código asociado a la variable
    string samplingPeriod = 6; // Periodo de muestreo como cadena
    int32 modbusAddress = 7; // Dirección Modbus
    string unitid = 8; // ID de la unidad
}

// Mensaje para una colección de AnalogicVariables
message AnalogicVariables {
    repeated AnalogicVariableDTO items = 1; // Lista de AnalogicVariableDTOs
}

// DTO Nullable para AnalogicVariable
message NullableAnalogicVariableDTO {
    oneof kind {
        google.protobuf.NullValue null = 1; // Representa un valor nulo
        AnalogicVariableDTO analogicVariable = 2; // El DTO actual de AnalogicVariable
    }
}

// Mensaje de solicitud para crear una AnalogicVariable
message CreateAnalogicVariableRequest {
    string name = 1; // Nombre de la variable
    VariableType type = 2; // Tipo de la variable
    bool isMeasurement = 3; // ¿Es una medición?
    string code = 4; // Código asociado a la variable
    string samplingPeriod = 5; // Periodo de muestreo como cadena
    int32 modbusAddress = 6; // Dirección Modbus
    string unitid = 7; // ID de la unidad
}

// Definición del mensaje Variable que puede ser analógica o digital
message Variable {
    oneof kind {
        AnalogicVariableDTO analogicvariable = 1;
        DigitalVariableDTO digitalvariable = 2; 
    } 
}
