syntax = "proto3";

option csharp_namespace = "ModbusData.GrpcProtos";

package GrpcProtos;

import "google/protobuf/wrappers.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/struct.proto";
import "common.proto"; 

// Definición del servicio para gestionar DigitalVariables
service DigitalVariable {
    rpc CreateDigitalVariable(CreateDigitalVariableRequest) returns (DigitalVariableDTO);
    rpc GetDigitalVariable(GetRequest) returns (NullableDigitalVariableDTO);
    rpc GetAllDigitalVariables(google.protobuf.Empty) returns (DigitalVariables);
    rpc UpdateDigitalVariable(DigitalVariableDTO) returns (google.protobuf.Empty);
    rpc DeleteDigitalVariable(DeleteRequest) returns (google.protobuf.Empty);
}

// DTO para DigitalVariable
message DigitalVariableDTO {
    string id = 1; // Identificador único
    string name = 2; // Nombre de la variable
    VariableType type = 3; // Tipo de la variable (Digital o Analógica)
    bool isMeasurement = 4; // ¿Es una medición?
    string code = 5; // Código asociado a la variable
    string samplingPeriod = 6; // Periodo de muestreo como cadena
    int32 modbusAddress = 7; // Dirección Modbus
    string unitid = 8; // ID de la unidad
}

// Mensaje para una colección de DigitalVariables
message DigitalVariables {
    repeated DigitalVariableDTO items = 1; // Lista de DigitalVariableDTOs
}

// DTO Nullable para DigitalVariable
message NullableDigitalVariableDTO {
    oneof kind {
        google.protobuf.NullValue null = 1; // Representa un valor nulo
        DigitalVariableDTO digitalVariable = 2; // El DTO actual de DigitalVariable
    }
}

// Mensaje de solicitud para crear una DigitalVariable
message CreateDigitalVariableRequest {
    string name = 1; // Nombre de la variable
    VariableType type = 2; // Tipo de la variable
    bool isMeasurement = 3; // ¿Es una medición?
    string code = 4; // Código asociado a la variable
    string samplingPeriod = 5; // Periodo de muestreo como cadena
    int32 modbusAddress = 6; // Dirección Modbus
    string unitid = 7; // ID de la unidad
}
