<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="analogicvariable.proto" />
    <None Remove="common.proto" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="Google.Protobuf" Version="3.29.2" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.67.0" />
    <PackageReference Include="MediatR" Version="12.4.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ModbusData.DataAccess\ModbusData.DataAccess.csproj" />
    <ProjectReference Include="..\ModbusData.Domain\ModbusData.Domain.csproj" />
    <ProjectReference Include="..\ModusData.Contracts\ModbusData.Contract.csproj" />
  </ItemGroup>
	<ItemGroup>
		<Protobuf Include="*.proto" GrpcServices=" Both" />
	</ItemGroup>
</Project>
