// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModbusData.DataAccess.Contexts;

#nullable disable

namespace ModbusData.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250114134437_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.27");

            modelBuilder.Entity("ModbusData.Domain.Entities.Device.SlaveDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("IpAddress");

                    b.Property<Guid?>("ModbusNetworkId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModbusNetworkId");

                    b.ToTable("SlaveDevices", (string)null);
                });

            modelBuilder.Entity("ModbusData.Domain.Entities.Modbus_Network.ModbusNetwork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("MasterIpAddress")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("MasterIpAddress");

                    b.HasKey("Id");

                    b.ToTable("ModbusNetworks", (string)null);
                });

            modelBuilder.Entity("ModbusData.Domain.Entities.Unit.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufactererName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Units", (string)null);
                });

            modelBuilder.Entity("ModbusData.Domain.Entities.Variables.Variable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMeasurement")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModbusAddress")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SamplingPeriod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SlaveDeviceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UnitId1")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SlaveDeviceId");

                    b.HasIndex("UnitId");

                    b.HasIndex("UnitId1");

                    b.ToTable("Variables");
                });

            modelBuilder.Entity("ModbusData.Domain.Entities.Variables.AnalogicVariable", b =>
                {
                    b.HasBaseType("ModbusData.Domain.Entities.Variables.Variable");

                    b.Property<double>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("REAL");

                    b.ToTable("AnalogicVariables", (string)null);
                });

            modelBuilder.Entity("ModbusData.Domain.Entities.Variables.DigitalVariable", b =>
                {
                    b.HasBaseType("ModbusData.Domain.Entities.Variables.Variable");

                    b.Property<short>("Value")
                        .HasMaxLength(1024)
                        .HasColumnType("INTEGER")
                        .HasColumnName("Value");

                    b.ToTable("DigitalVariables", (string)null);
                });

            modelBuilder.Entity("ModbusData.Domain.Entities.Device.SlaveDevice", b =>
                {
                    b.HasOne("ModbusData.Domain.Entities.Modbus_Network.ModbusNetwork", null)
                        .WithMany("Slaves")
                        .HasForeignKey("ModbusNetworkId");
                });

            modelBuilder.Entity("ModbusData.Domain.Entities.Variables.Variable", b =>
                {
                    b.HasOne("ModbusData.Domain.Entities.Device.SlaveDevice", null)
                        .WithMany("Variables")
                        .HasForeignKey("SlaveDeviceId");

                    b.HasOne("ModbusData.Domain.Entities.Unit.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModbusData.Domain.Entities.Unit.Unit", null)
                        .WithMany("Variables")
                        .HasForeignKey("UnitId1");
                });

            modelBuilder.Entity("ModbusData.Domain.Entities.Variables.AnalogicVariable", b =>
                {
                    b.HasOne("ModbusData.Domain.Entities.Variables.Variable", null)
                        .WithOne()
                        .HasForeignKey("ModbusData.Domain.Entities.Variables.AnalogicVariable", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModbusData.Domain.Entities.Variables.DigitalVariable", b =>
                {
                    b.HasOne("ModbusData.Domain.Entities.Variables.Variable", null)
                        .WithOne()
                        .HasForeignKey("ModbusData.Domain.Entities.Variables.DigitalVariable", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModbusData.Domain.Entities.Device.SlaveDevice", b =>
                {
                    b.Navigation("Variables");
                });

            modelBuilder.Entity("ModbusData.Domain.Entities.Modbus_Network.ModbusNetwork", b =>
                {
                    b.Navigation("Slaves");
                });

            modelBuilder.Entity("ModbusData.Domain.Entities.Unit.Unit", b =>
                {
                    b.Navigation("Variables");
                });
#pragma warning restore 612, 618
        }
    }
}
